apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-argo
  namespace: argo
spec:
  schedule: "2 16 * * *"
  timezone: "UTC"   # Default to local machine timezone
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Replace"      # Default to "Allow"
  successfulJobsHistoryLimit: 4     # Default 3
  failedJobsHistoryLimit: 4         # Default 1
  suspend: false                    # Set to "true" to suspend scheduling
  workflowSpec:
    entrypoint: whalesay
    templates:
      - name: whalesay
        container:
          image: docker/whalesay:latest
          command: [cowsay]
          args: ["🕓 hello argo"]
